Repository legend-exp/LegendDataManagement.jl, pull requests merged in 2024-09, with the labels that each got.

#63 Active and total volume calculation
  .github/workflows/CompatHelper.yml
  .github/workflows/DocPreviewCleanup.yml
  .github/workflows/TagBot.yml
  .github/workflows/ci.yml
  Project.toml
  src/LegendDataManagement.jl
  src/active_volume.jl
  src/legend_data.jl
  test/test_ext_ssd.jl
  test/test_legend_data.jl
Labels: enhancement

#68 Drop dependency on `Requires`
  Project.toml
  ext/LegendDataManagementLegendHDF5IOExt.jl
  src/LegendDataManagement.jl
Labels: dependencies

#70 Bugfix when parsing borehole taper in SSD extension
  ext/LegendDataManagementSolidStateDetectorsExt.jl
Labels: bug

#59 Simplified data loader
  .gitignore
  Project.toml
  docs/src/extensions.md
  ext/LegendDataManagementLegendHDF5IOExt.jl
  ext/LegendDataManagementSolidStateDetectorsExt.jl
  src/LegendDataManagement.jl
  src/active_volume.jl
  src/calfunc.jl
  src/calibration_functions.jl
  src/data_io.jl
  src/dataprod_config.jl
  src/evt_functions.jl
  src/filekey.jl
  src/legend_data.jl
  src/ljl_expressions.jl
  src/lprops.jl
  src/utils/data_utils.jl
  src/utils/pars_utils.jl
  src/utils/utils.jl
  test/test_ext_ssd.jl
  test/test_legend_data.jl
Labels: enhancement

#69 Add Downgrade CI
  .github/workflows/Downgrade.yml
  Project.toml
Labels: dependencies

#71 Bump compat for SolidStateDetectors in [weakdeps] to 0.10.2
  Project.toml
Labels: dependencies
