Repository legend-exp/LegendDataManagement.jl, pull requests merged in 2025-04, with the labels that each got.

#107 Update active volume calculation
  src/active_volume.jl
Labels: bug

#110 Add more methods to create SSD objects from metadata
  ext/LegendDataManagementSolidStateDetectorsExt.jl
  test/test_ext_ssd.jl
Labels: enhancement, ssd

#114 Parallel `read_ldata`
  docs/src/extensions.md
  ext/LegendDataManagementLegendHDF5IOExt.jl
  test/test_legend_data.jl
Labels: enhancement
