Repository legend-exp/LegendDataManagement.jl, pull requests merged in 2025-03, with the labels that each got.

#93 `LQ` calibration functions and `PSD` propfuncs
  src/calibration_functions.jl
Labels: bug, enhancement

#96 Bug Fix `search_disk`
  src/legend_data.jl
Labels: bug

#99 Update `get_plottitle`
  src/utils/plot_utils.jl
Labels: bug, enhancement

#97 `PMT` calibration + event level functions
  src/calibration_functions.jl
  src/evt_functions.jl
Labels: enhancement, dependencies

#100 Bug Fix PSD `calibration_functions`
  src/calibration_functions.jl
Labels: bug

#91 Add HPGeEnvironment
  Project.toml
  ext/LegendDataManagementSolidStateDetectorsExt.jl
  src/LegendDataManagement.jl
  src/hpge_environment.jl
  test/test_ext_ssd.jl
Labels: ssd

#104 Include `psd_usability` in `channelinfo`
  src/legend_data.jl
Labels: bug, enhancement

#106 Update `exposure` calculation
  src/exposure.jl
Labels: bug, enhancement

#108 Patch `exposure` calculation
  src/exposure.jl
Labels: bug

#109 Fix base method of `get_exposure`
  src/exposure.jl
Labels: bug
