Repository legend-exp/LegendDataManagement.jl, pull requests merged in 2025-05, with the labels that each got.

#115 Rename LQ `highcut`
  src/calibration_functions.jl
Labels: enhancement

#117 Patch `PropsDB` overrides
  src/props_db.jl
Labels: bug

#119 Define hierarchy of metadata values for dead layer thickness and bias voltage
  Project.toml
  docs/src/extensions.md
  ext/LegendDataManagementSolidStateDetectorsExt.jl
  test/test_ext_ssd.jl
Labels: ssd

#121 Patch `read_ldata` parallel read option
  ext/LegendDataManagementLegendHDF5IOExt.jl
Labels: bug
